[versions]
liquibase =  "5.0.1"
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
postgresql = "42.7.8"
spotless = "8.1.0"
errorprone = "2.45.0"
errorprone-plugin = "4.3.0"
nullaway = "0.12.15"
jspecify = "1.0.0"

[libraries]
liquibase-core = { group = "org.liquibase", name = "liquibase-core",version.ref = "liquibase"}
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
driver-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
errorprone = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorprone" }
nullaway = { group = "com.uber.nullaway", name = "nullaway", version.ref = "nullaway" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
spring-boot-gradle = { group = "org.springframework.boot", name="spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-dependency-management-gradle = { group = "io.spring.dependency-management", name="io.spring.dependency-management.gradle.plugin", version.ref = "spring-dependency-management"}
spotless-gradle = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
errorprone-gradle = { group = "net.ltgt.errorprone", name = "net.ltgt.errorprone.gradle.plugin", version.ref = "errorprone-plugin" }
