[versions]
liquibase =  "5.0.1"
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
postgresql = "42.7.8"
detekt = "1.23.8"
kotlin = "2.3.10"
ktlint = "14.0.1"

[libraries]
liquibase-core = { group = "org.liquibase", name = "liquibase-core",version.ref = "liquibase"}
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
driver-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
spring-boot-gradle = { group = "org.springframework.boot", name="spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-dependency-management-gradle = { group = "io.spring.dependency-management", name="io.spring.dependency-management.gradle.plugin", version.ref = "spring-dependency-management"}
detekt-gradle = { group = "io.gitlab.arturbosch.detekt", name = "io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
detekt-ktlint = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-ktlint-wrapper", version.ref = "ktlint" }
kotlin-gradle = {group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin"}
kotlin-spring-gradle = {group = "org.jetbrains.kotlin.plugin.spring", name = "org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin"}
ktlint-gradle = {group = "org.jlleitschuh.gradle.ktlint",name="org.jlleitschuh.gradle.ktlint.gradle.plugin",version.ref="ktlint"}
